/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Property.Property;
import Business.Property.PropertyDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dinesh
 */
public class CreateAdvertiseJPanel extends javax.swing.JPanel {

    JFileChooser imgChooser;
    private EcoSystem system;
    private UserAccount userAccount;
    BufferedImage img;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PropertyDirectory propertyDirectory;

    /**
     * Creates new form CreateAdvertiseJPanel
     */
    public CreateAdvertiseJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount useraccount, EcoSystem system) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.enterprise = enterprise;
            this.userAccount = useraccount;
            this.system = system;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
       disableLabels();
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imgupload.getWidth(), imgupload.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        stateTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bathroomTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bhkTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        imgupload = new javax.swing.JLabel();
        zipcodeTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCharge = new javax.swing.JTextField();
        homeNamelbl = new javax.swing.JLabel();
        imglbl = new javax.swing.JLabel();
        bhklbl = new javax.swing.JLabel();
        pricelbl = new javax.swing.JLabel();
        bathroomlbl = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(241, 241, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel2.setText("Name* :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 99, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel3.setText("City");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 172, -1, -1));
        jPanel1.add(cityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel6.setText("House Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 99, -1, -1));

        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        jPanel1.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 94, 180, -1));
        jPanel1.add(stateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 167, 180, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setText("State");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 172, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel8.setText("Upload Image* :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel10.setText("BHK:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));
        jPanel1.add(bathroomTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 180, -1));

        submitBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        submitBtn.setText("Save");
        submitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 105, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel4.setText("Pincode:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 260, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 56, 82));
        jLabel11.setText("HOUSE ADVERTISEMENT");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 24, -1, -1));

        uploadBtn.setBackground(new java.awt.Color(255, 255, 255));
        uploadBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uploadBtn.setText("Choose..");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 254, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel12.setText("Bathroom:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));
        jPanel1.add(bhkTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel13.setText("Price:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));
        jPanel1.add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 180, -1));
        jPanel1.add(imgupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 160, 100));
        jPanel1.add(zipcodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 180, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Charge");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));
        jPanel1.add(txtCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 180, -1));

        homeNamelbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homeNamelbl.setForeground(new java.awt.Color(255, 0, 0));
        homeNamelbl.setText("Please enter the name");
        jPanel1.add(homeNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, 20));

        imglbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        imglbl.setForeground(new java.awt.Color(255, 51, 51));
        imglbl.setText("Please upload the image of the house ");
        jPanel1.add(imglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 200, -1));

        bhklbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        bhklbl.setForeground(new java.awt.Color(255, 51, 51));
        bhklbl.setText("Please enter BHK value in integers");
        jPanel1.add(bhklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 210, -1));

        pricelbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        pricelbl.setForeground(new java.awt.Color(255, 51, 51));
        pricelbl.setText("Please enter price in 0.0 format");
        jPanel1.add(pricelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 200, -1));

        bathroomlbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        bathroomlbl.setForeground(new java.awt.Color(255, 51, 51));
        bathroomlbl.setText("Enter the bathroom in 0.0 format");
        jPanel1.add(bathroomlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed

        JFileChooser biofilechooser = new JFileChooser();
        biofilechooser.setDialogTitle("Choose Your File");
        biofilechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        // below code selects the file
        int returnvalbio = biofilechooser.showOpenDialog(this);
        if (returnvalbio == JFileChooser.APPROVE_OPTION) {
            File fileBio = biofilechooser.getSelectedFile();
            String pathBio = fileBio.getAbsolutePath();
            BufferedImage bioImage;
            try {
                // display the image in a Jlabel
                bioImage = ImageIO.read(fileBio);
                imgupload.setIcon(ResizeImage(pathBio));
                //lblPhotos.setIcon(new ImageIcon(bi));
            } catch (IOException e) {
                e.printStackTrace(); // todo: implement proper error handeling
            }
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxt.getText();
        String address = addressTxt.getText();
        String city = cityTxt.getText();
        String state = stateTxt.getText();
        String pincode = zipcodeTxt.getText();

        ImageIcon img = (ImageIcon) imgupload.getIcon();
        //blBioId.setIcon(personBioId);
        double price = 0.0;
        double bathroom = 0.0;

        price = Double.parseDouble(priceTxt.getText());
        int bhk = Integer.parseInt(bhkTxt.getText());
        bathroom = Double.parseDouble(bathroomTxt.getText());

        if (name.isEmpty() || address.isEmpty() || city.isEmpty() || state.isEmpty() || pincode.isEmpty() || price == 0.0 || img == null || bathroom == 0.0) {
            JOptionPane.showMessageDialog(null, "Please enter the missing field to continue!");
        }
        if(price==0.0 )
        {
            pricelbl.setVisible(true);
        }
        if(img==null)
        {
            imglbl.setVisible(true);
        }
        if(bhk==0)
        {
            bhklbl.setVisible(true);
        }
        if(bathroom==0.0)
        {
            bathroomlbl.setVisible(true);
        }
        else {
            disableLabels();
            String sellerName = this.userAccount.getEmployee().getName();
            Property property = new Property();
            property.setPropertyName(name);
            property.setStreet(address);
            property.setPincode(pincode);
            property.setCity(city);
            property.setState(state);
            property.setBhk(bhk);
            property.setBathroom(bathroom);
            property.setPrice(price);
            property.setStatus("Vacant");
            property.setUploadImg((ImageIcon) imgupload.getIcon());
            property.setSeller(userAccount);
            property.setPropertyID(propertyDirectory.generatePropertyID());
            propertyDirectory.addProperty(property);
            system.setPropertyDirectory(propertyDirectory);
            JOptionPane.showMessageDialog(null, "Advertisement Added!");
            emptyAllFields();
        }
    }//GEN-LAST:event_submitBtnActionPerformed
    
     public void emptyAllFields(){
        nameTxt.setText("");
        addressTxt.setText("");
        cityTxt.setText("");
        stateTxt.setText("");
        zipcodeTxt.setText("");
        imgupload.setText("");
        priceTxt.setText("");
        bhkTxt.setText("");
        bathroomTxt.setText("");
     }
 public void disableLabels()
 {
      homeNamelbl.setVisible(false);
        bhklbl.setVisible(false);
        imglbl.setVisible(false);
        pricelbl.setVisible(false);
        bathroomlbl.setVisible(false);
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField bathroomTxt;
    private javax.swing.JLabel bathroomlbl;
    private javax.swing.JTextField bhkTxt;
    private javax.swing.JLabel bhklbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel homeNamelbl;
    private javax.swing.JLabel imglbl;
    private javax.swing.JLabel imgupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JTextField zipcodeTxt;
    // End of variables declaration//GEN-END:variables
}
