package userinterface.SellerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class SellerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public SellerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        manageAdvertise();

    }

    private void manageAdvertise() {
        manageAdvertisePanel.setBackground(new Color(236, 113, 107));
        manageBuyer.setBackground(new Color(215, 81, 81));
        manageUserProfile.setBackground(new Color(215, 81, 81));
        manageHousesPanel.setBackground(new Color(215, 81, 81));
        CreateAdvertiseJPanel advrtPanel = new CreateAdvertiseJPanel(userProcessContainer, enterprise, account, system);
        rightSystemAdminPanel.add("advrtPanel",advrtPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageBuyers() {
        manageBuyer.setBackground(new Color(236, 113, 107));
        manageAdvertisePanel.setBackground(new Color(215, 81, 81));
        manageUserProfile.setBackground(new Color(215, 81, 81));
        manageHousesPanel.setBackground(new Color(215, 81, 81));
       //ManageBuyerJPanel mngBuyerPanel = new ManageBuyerJPanel(userProcessContainer, enterprise, account, system);
      // userProcessContainer.add("ManageBuyerJPanel", mngBuyerPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }

    private void manageUsers() {
        manageUserProfile.setBackground(new Color(236, 113, 107));
        manageAdvertisePanel.setBackground(new Color(215, 81, 81));
        manageBuyer.setBackground(new Color(215, 81, 81));
        manageHousesPanel.setBackground(new Color(215, 81, 81));
        ManageHouseJPanel mngHousesPanel = new ManageHouseJPanel(userProcessContainer, enterprise, account, system);
        rightSystemAdminPanel.add("ManageHouseJPanel", mngHousesPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageRequests() {
        manageHousesPanel.setBackground(new Color(236, 113, 107));
        manageUserProfile.setBackground(new Color(215, 81, 81));
        manageAdvertisePanel.setBackground(new Color(215, 81, 81));
        manageBuyer.setBackground(new Color(215, 81, 81));
    ManageSellerProfileJPanel manageSellerProfileJPanel = new ManageSellerProfileJPanel(userProcessContainer, system, account);
      userProcessContainer.add("ManageInspectorJPanel", manageSellerProfileJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        manageAdvertisePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageAdvertise = new javax.swing.JLabel();
        manageBuyer = new javax.swing.JPanel();
        manageProfile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manageUserProfile = new javax.swing.JPanel();
        manageHouses = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        manageHousesPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        rightSystemAdminPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1338, 840));
        setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(215, 81, 81));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));
        systemAdminPanel.setPreferredSize(new java.awt.Dimension(1338, 840));

        jPanel3.setBackground(new java.awt.Color(215, 81, 81));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 840));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 840));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAdvertisePanel.setBackground(new java.awt.Color(215, 81, 81));
        manageAdvertisePanel.setToolTipText("");
        manageAdvertisePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageAdvertisePanelMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(215, 81, 81));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/best.png"))); // NOI18N
        jLabel2.setToolTipText("");

        manageAdvertise.setBackground(new java.awt.Color(215, 81, 81));
        manageAdvertise.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageAdvertise.setText("Create Advertise");
        manageAdvertise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageAdvertiseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageAdvertisePanelLayout = new javax.swing.GroupLayout(manageAdvertisePanel);
        manageAdvertisePanel.setLayout(manageAdvertisePanelLayout);
        manageAdvertisePanelLayout.setHorizontalGroup(
            manageAdvertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAdvertisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAdvertise, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        manageAdvertisePanelLayout.setVerticalGroup(
            manageAdvertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAdvertisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageAdvertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(manageAdvertise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(manageAdvertisePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, -1));

        manageBuyer.setBackground(new java.awt.Color(215, 81, 81));
        manageBuyer.setToolTipText("");
        manageBuyer.setPreferredSize(new java.awt.Dimension(264, 48));
        manageBuyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageBuyerMousePressed(evt);
            }
        });

        manageProfile.setBackground(new java.awt.Color(215, 81, 81));
        manageProfile.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageProfile.setText("Manage Profile");
        manageProfile.setPreferredSize(new java.awt.Dimension(115, 16));

        jLabel6.setBackground(new java.awt.Color(215, 81, 81));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/manager24x.png"))); // NOI18N

        javax.swing.GroupLayout manageBuyerLayout = new javax.swing.GroupLayout(manageBuyer);
        manageBuyer.setLayout(manageBuyerLayout);
        manageBuyerLayout.setHorizontalGroup(
            manageBuyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageBuyerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(manageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageBuyerLayout.setVerticalGroup(
            manageBuyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageBuyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageBuyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(manageBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 40));

        manageUserProfile.setBackground(new java.awt.Color(215, 81, 81));
        manageUserProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageUserProfileMousePressed(evt);
            }
        });

        manageHouses.setBackground(new java.awt.Color(215, 81, 81));
        manageHouses.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageHouses.setText("Manage Houses");
        manageHouses.setPreferredSize(new java.awt.Dimension(115, 16));

        jLabel7.setBackground(new java.awt.Color(215, 81, 81));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-houses-48.png"))); // NOI18N

        javax.swing.GroupLayout manageUserProfileLayout = new javax.swing.GroupLayout(manageUserProfile);
        manageUserProfile.setLayout(manageUserProfileLayout);
        manageUserProfileLayout.setHorizontalGroup(
            manageUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUserProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(manageHouses, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        manageUserProfileLayout.setVerticalGroup(
            manageUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageHouses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(manageUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("SELLER WORK AREA ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 20));

        manageHousesPanel.setBackground(new java.awt.Color(215, 81, 81));
        manageHousesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageHousesPanelMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout manageHousesPanelLayout = new javax.swing.GroupLayout(manageHousesPanel);
        manageHousesPanel.setLayout(manageHousesPanelLayout);
        manageHousesPanelLayout.setHorizontalGroup(
            manageHousesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHousesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        manageHousesPanelLayout.setVerticalGroup(
            manageHousesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHousesPanelLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(manageHousesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 40));

        rightSystemAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightSystemAdminPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightSystemAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdvertiseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdvertiseMousePressed
        manageAdvertise();
    }//GEN-LAST:event_manageAdvertiseMousePressed

    private void manageAdvertisePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdvertisePanelMousePressed
        // TODO add your handling code here:
        manageAdvertise();
    }//GEN-LAST:event_manageAdvertisePanelMousePressed

    private void manageBuyerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBuyerMousePressed
        // TODO add your handling code here:
        manageBuyers();
    }//GEN-LAST:event_manageBuyerMousePressed

    private void manageUserProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserProfileMousePressed
        manageUsers();
    }//GEN-LAST:event_manageUserProfileMousePressed

    private void manageHousesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageHousesPanelMousePressed
        // TODO add your handling code here:
        manageRequests();
    }//GEN-LAST:event_manageHousesPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manageAdvertise;
    private javax.swing.JPanel manageAdvertisePanel;
    private javax.swing.JPanel manageBuyer;
    private javax.swing.JLabel manageHouses;
    private javax.swing.JPanel manageHousesPanel;
    private javax.swing.JLabel manageProfile;
    private javax.swing.JPanel manageUserProfile;
    private javax.swing.JPanel rightSystemAdminPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables

}
