
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellerRole;


import Business.Enterprise.Enterprise;
import java.awt.CardLayout;

import Business.EcoSystem;
import Business.Seller.SellerDirectory;
import Business.UserAccount.UserAccount;

import javax.swing.JPanel;

/**
 *
 * @author anusha
 */
public class SellerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private SellerDirectory sellerDirectory;
    /**
     * Creates new form SellerWorkAreaJPanel1
     */
 private Enterprise enterprise;

    
    public SellerWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,UserAccount useraccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=useraccount;

    }

    public SellerWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount account) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuyers = new javax.swing.JButton();
        btnAdvrt = new javax.swing.JButton();
        btnInspectors = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnManageHouse = new javax.swing.JButton();

        btnBuyers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuyers.setText("Manage Buyers");
        btnBuyers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyersActionPerformed(evt);
            }
        });

        btnAdvrt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdvrt.setText("Create Advertise");
        btnAdvrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvrtActionPerformed(evt);
            }
        });

        btnInspectors.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInspectors.setText("Manage Inspector");
        btnInspectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInspectorsActionPerformed(evt);
            }
        });

        btnServices.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnServices.setText("Manage Invoices");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnManageHouse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnManageHouse.setText("Manage Houses");
        btnManageHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInspectors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdvrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuyers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAdvrt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnBuyers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnInspectors, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvrtActionPerformed
        // TODO add your handling code here:
         CreateAdvertiseJPanel advrtPanel = new CreateAdvertiseJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("CreateAdvertiseJPanel", advrtPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdvrtActionPerformed

    private void btnBuyersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyersActionPerformed
        // TODO add your handling code here:
        ManageBuyerJPanel mngBuyerPanel = new ManageBuyerJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageBuyerJPanel", mngBuyerPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyersActionPerformed

    private void btnInspectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspectorsActionPerformed
        // TODO add your handling code here:
        ManageInspectorJPanel mngInspectorPanel = new ManageInspectorJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageInspectorJPanel", mngInspectorPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInspectorsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
        ManageInvoicesJPanel mngServicesPanel = new ManageInvoicesJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageServicesJPanel", mngServicesPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnManageHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHouseActionPerformed
        // TODO add your handling code here:
         ManageHouseJPanel mngHousesPanel = new ManageHouseJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageHouseJPanel", mngHousesPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvrt;
    private javax.swing.JButton btnBuyers;
    private javax.swing.JButton btnInspectors;
    private javax.swing.JButton btnManageHouse;
    private javax.swing.JButton btnServices;
    // End of variables declaration//GEN-END:variables
}
=======
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellerRole;


import Business.Enterprise.Enterprise;
import java.awt.CardLayout;

import Business.EcoSystem;
import Business.Seller.SellerDirectory;
import Business.UserAccount.UserAccount;

import javax.swing.JPanel;

/**
 *
 * @author anusha
 */
public class SellerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private SellerDirectory sellerDirectory;
    /**
     * Creates new form SellerWorkAreaJPanel1
     */
 private Enterprise enterprise;

    
    public SellerWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,UserAccount useraccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=useraccount;

    }

    public SellerWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount account) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuyers = new javax.swing.JButton();
        btnAdvrt = new javax.swing.JButton();
        btnInspectors = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnManageHouse = new javax.swing.JButton();

        btnBuyers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuyers.setText("Manage Buyers");
        btnBuyers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyersActionPerformed(evt);
            }
        });

        btnAdvrt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdvrt.setText("Create Advertise");
        btnAdvrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvrtActionPerformed(evt);
            }
        });

        btnInspectors.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInspectors.setText("Manage Inspector");
        btnInspectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInspectorsActionPerformed(evt);
            }
        });

        btnServices.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnServices.setText("Manage Invoices");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnManageHouse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnManageHouse.setText("Manage Houses");
        btnManageHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInspectors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdvrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuyers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAdvrt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnBuyers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnInspectors, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvrtActionPerformed
        // TODO add your handling code here:
         CreateAdvertiseJPanel advrtPanel = new CreateAdvertiseJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("CreateAdvertiseJPanel", advrtPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdvrtActionPerformed

    private void btnBuyersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyersActionPerformed
        // TODO add your handling code here:
        ManageBuyerJPanel mngBuyerPanel = new ManageBuyerJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageBuyerJPanel", mngBuyerPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyersActionPerformed

    private void btnInspectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspectorsActionPerformed
        // TODO add your handling code here:
        ManageInspectorJPanel mngInspectorPanel = new ManageInspectorJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageInspectorJPanel", mngInspectorPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInspectorsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
        ManageInvoicesJPanel mngServicesPanel = new ManageInvoicesJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageServicesJPanel", mngServicesPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnManageHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHouseActionPerformed
        // TODO add your handling code here:
         ManageHouseJPanel mngHousesPanel = new ManageHouseJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManageHouseJPanel", mngHousesPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvrt;
    private javax.swing.JButton btnBuyers;
    private javax.swing.JButton btnInspectors;
    private javax.swing.JButton btnManageHouse;
    private javax.swing.JButton btnServices;
    // End of variables declaration//GEN-END:variables
}

