/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BuyerRole;

import Business.Buyer.BuyerDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Property.PropertyDirectory;
import Business.Seller.SellerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dinesh
 */
public class viewJobsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJobsJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private SellerDirectory sellerDirectory;
    private PropertyDirectory propertyDirectory;
    private BuyerDirectory buyerDirectory;
    private Enterprise enterprise; 

    /**
     * Creates new form BuyerWorkAreaJpanel
     */
    public viewJobsJPanel(JPanel userProcess, EcoSystem system,Enterprise enterprsie, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.system = system;
         this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
        this.buyerDirectory = (system.getBuyerDirectory() == null) ? new BuyerDirectory() : system.getBuyerDirectory();
        this.sellerDirectory = (system.getSellerDirectory() == null) ? new SellerDirectory() : system.getSellerDirectory();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHireInspector1 = new javax.swing.JButton();
        btnViewElectrician = new javax.swing.JButton();
        btnViewPlumber = new javax.swing.JButton();
        btnViewPacker = new javax.swing.JButton();
        btnViewPhoto = new javax.swing.JButton();
        btnViewCleaner = new javax.swing.JButton();
        btnViewManager = new javax.swing.JButton();
        btnViewBuilder = new javax.swing.JButton();

        btnHireInspector1.setText("View Inspector Jobs");
        btnHireInspector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHireInspector1ActionPerformed(evt);
            }
        });

        btnViewElectrician.setText("View Electrician Jobs");
        btnViewElectrician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewElectricianActionPerformed(evt);
            }
        });

        btnViewPlumber.setText("View Plumber Jobs");
        btnViewPlumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPlumberActionPerformed(evt);
            }
        });

        btnViewPacker.setText("View Packer Jobs");
        btnViewPacker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPackerActionPerformed(evt);
            }
        });

        btnViewPhoto.setText("View Photographer Jobs");
        btnViewPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPhotoActionPerformed(evt);
            }
        });

        btnViewCleaner.setText("View Cleaner Jobs");
        btnViewCleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCleanerActionPerformed(evt);
            }
        });

        btnViewManager.setText("View Property Manager Jobs");
        btnViewManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewManagerActionPerformed(evt);
            }
        });

        btnViewBuilder.setText("View Builder Jobs");
        btnViewBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBuilderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewElectrician, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(btnHireInspector1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewManager, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewPacker, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewPlumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(436, 436, 436))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnHireInspector1)
                .addGap(18, 18, 18)
                .addComponent(btnViewElectrician)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPlumber)
                .addGap(12, 12, 12)
                .addComponent(btnViewPacker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPhoto)
                .addGap(13, 13, 13)
                .addComponent(btnViewCleaner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewBuilder)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHireInspector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHireInspector1ActionPerformed
        // TODO add your handling code here:
        ManageInspectorActivity manageInspectorActivity = new ManageInspectorActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("manageInspectorActivity", manageInspectorActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHireInspector1ActionPerformed

    private void btnViewElectricianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewElectricianActionPerformed
        ManageElectricianActivity manageElectricianActivity = new ManageElectricianActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("manageElectricianActivity", manageElectricianActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewElectricianActionPerformed

    private void btnViewPlumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPlumberActionPerformed
        ManagePlumberActivity managePlumberActivity = new ManagePlumberActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("ManagePlumberActivity", managePlumberActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPlumberActionPerformed

    private void btnViewPackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPackerActionPerformed
        ManagePackerActivity managePackerActivity = new ManagePackerActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("ManagePackerActivity", managePackerActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPackerActionPerformed

    private void btnViewPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPhotoActionPerformed
        ManagePhotoActivity ManagePhotoActivity = new ManagePhotoActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("ManagePhotoActivity", ManagePhotoActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPhotoActionPerformed

    private void btnViewCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCleanerActionPerformed
        ManageCleanerActivity ManageCleanerActivity = new ManageCleanerActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("ManageCleanerActivity", ManageCleanerActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewCleanerActionPerformed

    private void btnViewManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewManagerActionPerformed
        ManageManagerActivity manageManagerActivity = new ManageManagerActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("ManageManagerActivity", manageManagerActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewManagerActionPerformed

    private void btnViewBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBuilderActionPerformed
        ManageBuilderActivity manageManagerActivity = new ManageBuilderActivity(userProcessContainer,userAccount, system );
        userProcessContainer.add("ManageManagerActivity", manageManagerActivity);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewBuilderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHireInspector1;
    private javax.swing.JButton btnViewBuilder;
    private javax.swing.JButton btnViewCleaner;
    private javax.swing.JButton btnViewElectrician;
    private javax.swing.JButton btnViewManager;
    private javax.swing.JButton btnViewPacker;
    private javax.swing.JButton btnViewPhoto;
    private javax.swing.JButton btnViewPlumber;
    // End of variables declaration//GEN-END:variables
}
