

package userinterface.PackersMoversRole;

import Business.Buyer.BuyerDirectory;
import Business.CleaningRequest.CleaningRequestDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.PackerRequest.PackerRequestDirectory;
import Business.Property.PropertyDirectory;
import Business.Seller.SellerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

import userinterface.PackersMoversRole.ManagePackerJPanel;
import userinterface.PackersMoversRole.ViewDetailsJPanel;

/**
 *
 * @author  raunak
 */
public class PackersMoversWorkAreaJPanel extends javax.swing.JPanel {
    
   private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private SellerDirectory sellerDirectory;
    private PropertyDirectory propertyDirectory;
    private BuyerDirectory buyerDirectory;
    private PackerRequestDirectory packerRequestDirectory;

    
     public PackersMoversWorkAreaJPanel(JPanel userProcess, EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.system = system;
        this.userAccount = userAccount;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
        this.buyerDirectory = (system.getBuyerDirectory() == null) ? new BuyerDirectory() : system.getBuyerDirectory();
        this.packerRequestDirectory = (system.getPackerRequestDirectory()== null) ? new PackerRequestDirectory(): system.getPackerRequestDirectory();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageProfile = new javax.swing.JButton();
        btnViewJobs = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageProfile.setText("Manage Profile");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });
        add(btnManageProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, 30));

        btnViewJobs.setText("View Jobs");
        btnViewJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewJobsActionPerformed(evt);
            }
        });
        add(btnViewJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewJobsActionPerformed
        ViewDetailsJPanel viewJobsJPanel = new ViewDetailsJPanel(userProcessContainer, system, userAccount);
        userProcessContainer.add("ViewDetailsJPanel", viewJobsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewJobsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        ManagePackerJPanel managePackerJPanel = new ManagePackerJPanel(userProcessContainer, system, userAccount);
        userProcessContainer.add("ManagePackerJPanel", managePackerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageProfileActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnViewJobs;
    // End of variables declaration//GEN-END:variables
    
}
