/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Agent.Agent;
import Business.Agent.AgentDirectory;
import Business.Builder.Builder;
import Business.Builder.BuilderDirectory;
import Business.Buyer.Buyer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Inspector.Inspector;
import Business.Inspector.InspectorDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Photographer.Photographer;
import Business.Photographer.PhotographerDirectory;
import Business.PropertyManager.PropertyManager;
import Business.PropertyManager.PropertyManagerDirectory;
import Business.Role.AgentRole;
import Business.Role.BuilderRole;
import Business.Role.BuyerRole;
import Business.Role.PhotographerRole;
import Business.Role.PropertyManagerRole;
import Business.Role.Role;
import Business.Role.SellerRole;
import Business.Seller.Seller;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CreateSystemUsersJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private PhotographerDirectory photographerDirectory;
    private InspectorDirectory inspectorDirectory;
    private AgentDirectory agentDirectory;
    private BuilderDirectory builderDirectory;
    private PropertyManagerDirectory propertyManagerDirectory;
    private final DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public enum RoleType {
        Admin("Admin"),
        Buyer("Buyer"),
        Seller("Seller"),
        Inspector("Inspector"),
        Agent("Agent"),
        Builder("Builder"),
        PropertyManager("Property Manager"),
        Electrician("Electrician"),
        Miscellaneous("Miscellaneous"),
        Cleaning("Cleaning"),
        PackersMovers("Movers & Packers"),
        Photographer("Photographer"),
        Plumbing("Plumbing"),
        GovermentEmployee("Goverment Employee");

        private String value;

        private RoleType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return value;
        }
    }

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public CreateSystemUsersJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.photographerDirectory = (system.getPhotographerDirectory() == null) ? new PhotographerDirectory() : system.getPhotographerDirectory();
        this.inspectorDirectory = (system.getInspectorDirectory() == null) ? new InspectorDirectory() : system.getInspectorDirectory();
        this.agentDirectory = (system.getAgentDirectory() == null) ? new AgentDirectory() : system.getAgentDirectory();
        this.builderDirectory = (system.getBuilderDirectory() == null) ? new BuilderDirectory() : system.getBuilderDirectory();
        populateComboBox();
    }

    public void populateComboBox() {
        comboboxRole.removeAllItems();
        for (RoleType role : RoleType.values()) {
            comboboxRole.addItem(role.getValue());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        comboboxRole = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Create User");

        jLabel2.setText("Name:");

        lblPassword.setText("Password:");

        jLabel4.setText("Username:");

        lblEmail.setText("Email:");

        jLabel6.setText("Role:");

        comboboxRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addGap(24, 24, 24)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(98, 98, 98)
                        .addComponent(comboboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(47, 47, 47)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btnSave)
                        .addGap(107, 107, 107)
                        .addComponent(backJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(comboboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(backJButton))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            String emailAddress = txtEmail.getText();
            String username = lblUsername.getText();
            String name = txtFullName.getText();
            String password = txtPassword.getText();
            String userType = comboboxRole.getSelectedItem().toString();
            for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getUsername().equals(username)) {
                    JOptionPane.showMessageDialog(null, "Username should be unique. UserName is already in use.");
                    return;
                }
            }
            if (usernamePatternCorrect() == false) {
                lblUsername.setForeground(Color.red);
                txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
                return;
            } else {
                lblUsername.setForeground(Color.BLACK);
                txtEmail.setBorder(BorderFactory.createLineBorder(Color.black));
            }
            if (passwordPatternCorrect() == false) {
                lblPassword.setForeground(Color.red);
                txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            } else {
                lblPassword.setForeground(Color.BLACK);
                txtPassword.setBorder(BorderFactory.createLineBorder(Color.black));
            }
            if (userType == "Photographer") {
                Photographer photographer = new Photographer();
                photographer.setPhotographerName(name);
                photographer.setPhotographerEmail(emailAddress);
                photographer.setPhotographerNo(photographerDirectory.generatePhotographerID());
                photographerDirectory.addPhotographer(photographer);
                Employee employee = system.getEmployeeDirectory().createEmployee(photographer.getPhotographerNo());
                PhotographerRole role = new PhotographerRole();
                system.setPhotographerDirectory(photographerDirectory);
                UserAccount ua = system.getUserAccountDirectory().createUserAccount(username, password, employee, role, false, name, emailAddress, "Photographer");
            }
            else if(userType == "Inspector")
            {
                Inspector inspector = new Inspector();
                inspector.setInspectorName(name);
                inspector.setInspectorEmail(emailAddress);
                inspector.setInspectorNo(photographerDirectory.generatePhotographerID());
                inspectorDirectory.addInspector(inspector);
                Employee employee = system.getEmployeeDirectory().createEmployee(inspector.getInspectorNo());
                PhotographerRole role = new PhotographerRole();
                system.setPhotographerDirectory(photographerDirectory);
                UserAccount ua = system.getUserAccountDirectory().createUserAccount(username, password, employee, role, false, name, emailAddress, "Inspector");
            }
            else if(userType == "Agent")
            {
                Agent agent = new Agent();
                agent.setAgentName(name);
                agent.setAgentEmail(emailAddress);
                agent.setAgentNo(agentDirectory.generateAgentID());
                agentDirectory.addAgent(agent);
                Employee employee = system.getEmployeeDirectory().createEmployee(agent.getAgentNo());
                AgentRole role = new AgentRole();
                system.setAgentDirectory(agentDirectory);
                UserAccount ua = system.getUserAccountDirectory().createUserAccount(username, password, employee, role, false, name, emailAddress, "Agent");
            }
            else if(userType == "Builder")
            {
                Builder builder = new Builder();
                builder.setBuilderName(name);
                builder.setBuilderEmail(emailAddress);
                builder.setBuilderNo(agentDirectory.generateAgentID());
                builderDirectory.addBuilder(builder);
                Employee employee = system.getEmployeeDirectory().createEmployee(builder.getBuilderNo());
                BuilderRole role = new BuilderRole();
                system.setBuilderDirectory(builderDirectory);
                UserAccount ua = system.getUserAccountDirectory().createUserAccount(username, password, employee, role, false, name, emailAddress, "Builder");
            }
            else if(userType == "Property Manager")
            {
                PropertyManager propertyManager = new PropertyManager();
                propertyManager.setPropertyName(name);
                propertyManager.setPropertyEmail(emailAddress);
                propertyManager.setPropertyNo(propertyManagerDirectory.generatePropertyManagerID());
                propertyManagerDirectory.addPropertyManager(propertyManager);
                Employee employee = system.getEmployeeDirectory().createEmployee(propertyManager.getPropertyNo());
                PropertyManagerRole role = new PropertyManagerRole();
                system.setPropertyManagerDirectory(propertyManagerDirectory);
                UserAccount ua = system.getUserAccountDirectory().createUserAccount(username, password, employee, role, false, name, emailAddress, "Property Manager");
            }
            JOptionPane.showMessageDialog(null, userType + " added successfully");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    private boolean usernamePatternCorrect() {
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(txtEmail.getText());
        boolean b = m.matches();
        return b;
    }

    private boolean passwordPatternCorrect() {
        Pattern p1;
        p1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1 = p1.matcher(txtPassword.getText());
        boolean b1 = m1.matches();
        return b1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboboxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField lblUsername;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
