

package userinterface.ElectricianRole;

import Business.Buyer.BuyerDirectory;
import Business.EcoSystem;
import Business.ElectricianRequest.ElectricianRequest;
import Business.ElectricianRequest.ElectricianRequestDirectory;
import Business.Enterprise.Enterprise;
import Business.Property.Property;
import Business.Property.PropertyDirectory;
import Business.Seller.SellerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Dinesh
 */
public class ElectricianWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private ElectricianRequestDirectory electricianRequestDirectory;
    private SellerDirectory sellerDirectory;
    private PropertyDirectory propertyDirectory;
    private BuyerDirectory buyerDirectory;
    private ElectricianRequestDirectory ElectricianRequestDirectory;

    /** Creates new form AdminWorkAreaJPanel */
    public ElectricianWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount userAccount ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount=userAccount;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
        this.buyerDirectory = (system.getBuyerDirectory() == null) ? new BuyerDirectory() : system.getBuyerDirectory();
        this.electricianRequestDirectory = (system.getElectricianRequestDirectory()== null) ? new ElectricianRequestDirectory(): system.getElectricianRequestDirectory();
    }
    
     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        viewJobsBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Manage Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, 30));

        viewJobsBtn.setText("View Jobs");
        viewJobsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJobsBtnActionPerformed(evt);
            }
        });
        add(viewJobsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void viewJobsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJobsBtnActionPerformed
        ViewElectricianJobsJPanel viewJobsJPanel = new ViewElectricianJobsJPanel(userProcessContainer, system, userAccount);
        userProcessContainer.add("viewJobsJPanel", viewJobsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewJobsBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManageElectricianJPanel manageElectricianJPanel = new ManageElectricianJPanel(userProcessContainer, system, userAccount);
        userProcessContainer.add("viewJobsJPanel", manageElectricianJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton viewJobsBtn;
    // End of variables declaration//GEN-END:variables
    
}
